package com.example.womensafetylegaladvisor;

public class AdvocateData {
    public static final String[][] ADVOCATES = {
            {"Neelam Patil", "MG Road", "411017", "Pune", "Maharashtra", "MH12345", "Bombay High court", "Criminal Law", "Marathi, English", "Cyber Crime", "5yrs", "9898989898", "neelam.patil@example.com", "Experienced in criminal law with a specialization in cyber crime.", "images/layout_img/msg1.png"},
            {"Rohit Sharma", "Baner Road", "411045", "Pune", "Maharashtra", "MH54321", "Pune District court", "Family Law", "Hindi, English", "Divorce Cases", "7yrs", "9876543210", "rohit.sharma@example.com", "Specializes in family law, focusing on divorce cases.", "images/layout_img/msg2.png"},
            {"Sneha Kulkarni", "Paud Road", "411038", "Pune", "Maharashtra", "MH67890", "Bombay High court", "Corporate Law", "Marathi, English", "Mergers & Acquisitions", "10yrs", "9865321470", "sneha.kulkarni@example.com", "Expert in corporate law, with extensive experience in mergers and acquisitions.", "images/layout_img/msg1.png"},
            {"Aniket Deshmukh", "Magarpatta city", "411028", "Pune", "Maharashtra", "MH98765", "Pune District court", "Civil Law", "Marathi, Hindi", "Property Disputes", "4yrs", "9856473210", "aniket.deshmukh@example.com", "Focuses on civil law with a specialization in property disputes.", "images/layout_img/msg1.png"},
            {"Priya Nair", "Wakad Road", "411057", "Pune", "Maharashtra", "MH11223", "Bombay High court", "Intellectual Property Law", "English, Hindi", "Patent Law", "8yrs", "9845123670", "priya.nair@example.com", "Specializes in intellectual property law, particularly patent law.", "images/user_img.jpg"},
            {"Vishal Patil", "IT Park Road", "411007", "Pune", "Maharashtra", "MH33221", "Pune District court", "Tax Law", "Marathi, English", "Income Tax", "6yrs", "9821475630", "vishal.patil@example.com", "Experienced in tax law with a focus on income tax.", "images/layout_img/msg3.png"},
            {"Rajesh Gupta", "Phoenix Road", "411014", "Pune", "Maharashtra", "MH44556", "Pune District court", "Labor Law", "Hindi, English", "Workplace Disputes", "12yrs", "9812345670", "rajesh.gupta@example.com", "Specializes in labor law, focusing on workplace disputes.", "images/user_img.jpg"},
            {"Kavita Rao", "Central Avenue", "411006", "Pune", "Maharashtra", "MH55667", "Bombay High court", "Environmental Law", "English, Marathi", "Pollution Control", "9yrs", "9801234567", "kavita.rao@example.com", "Expert in environmental law with a specialization in pollution control.", "images/layout_img/msg3.png"},
            {"Suresh Mehta", "JM Road", "411004", "Pune", "Maharashtra", "MH66778", "Pune District court", "Consumer Law", "Hindi, English", "Consumer Rights", "15yrs", "9798765432", "suresh.mehta@example.com", "Specializes in consumer law, with extensive experience in consumer rights.", "images/user_img.jpg"},
            {"Anita Verma", "MG Road", "411001", "Pune", "Maharashtra", "MH77889", "Bombay High court", "Constitutional Law", "English, Hindi", "Fundamental Rights", "20yrs", "9787654321", "anita.verma@example.com", "Expert in constitutional law, focusing on fundamental rights.", "images/layout_img/msg4.png"}
    };
}
