package com.example.womensafetylegaladvisor;

public class ResourceData {
    public static final String[][] RESOURCE = {
            {"Understanding and Combating Domestic Violence", "This resource provides an in-depth look at domestic violence, including the legal definitions, types of abuse, and protective measures available. It covers restraining orders, legal proceedings for domestic violence cases, and the support systems in place for victims. Authored by Jane Doe."},
            {"Navigating Sexual Harassment Laws in the Workplace", "A comprehensive guide to understanding sexual harassment in the workplace. This resource details the legal framework protecting women from harassment, how to file a complaint, and the steps involved in seeking justice. It also includes case studies and advice on workplace policies. Authored by Sarah Lee."},
            {"Legal Rights of Women in Cases of Sexual Assault", "This resource outlines the legal rights and protections available to women who are victims of sexual assault. It includes information on reporting the crime, the legal process, victim support services, and the role of forensic evidence. Authored by Emily Clark."},
            {"Understanding Cyberstalking and Online Harassment Laws", "A detailed guide on the legal aspects of cyberstalking and online harassment. This resource explains the laws that protect women from online threats, how to report incidents, and the legal actions that can be taken. It also discusses digital safety tips and resources for victims. Authored by Lisa Wong."},
            {"Women's Rights in Divorce and Child Custody Cases", "An extensive resource covering the legal rights of women in divorce and child custody cases. It includes information on property division, spousal support, and child custody arrangements, as well as the legal process and considerations for women. Authored by Jennifer Taylor."},
            {"Protection and Legal Recourse Against Human Trafficking", "This resource provides an in-depth understanding of human trafficking, including the signs, legal definitions, and protective laws. It outlines the legal recourse available to victims and the support services provided by various organizations. Authored by Anna Rodriguez."},
            {"Navigating the Legal System for Workplace Discrimination", "A comprehensive guide to understanding workplace discrimination laws and how they protect women. This resource covers the types of discrimination, how to file a complaint, and the legal remedies available. It also provides tips on documenting incidents and seeking legal advice. Authored by Michelle Johnson."},
            {"Understanding Maternity Rights and Workplace Protections", "This resource details the legal rights and protections for pregnant women and new mothers in the workplace. It includes information on maternity leave, workplace accommodations, and the legal framework ensuring these rights. Authored by Karen White."},
            {"Legal Support and Rights for Immigrant Women", "An in-depth look at the legal rights and support available to immigrant women. This resource covers visa options, protections against exploitation and abuse, and the legal resources available to immigrant women facing legal challenges. Authored by Sophia Hernandez."},
            {"Combating Gender-Based Violence: Legal Framework and Support", "A detailed resource on the legal framework addressing gender-based violence. It includes information on legal protections, how to seek help, and the role of law enforcement and support services in protecting victims. Authored by Rachel Thompson."}
    };
}
